version: '3.9'
services:
  metabolism-app:
    build: 
      context: .
      dockerfile: dockerfile
    command: "npm run dev"
    container_name: metabolism-app
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - .:/metabolism-app
      - /metabolism-app/node_modules