import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local'
import "../styles/globals.css";
import { ThemeProvider } from "@mui/material/styles";
import theme from "../utils/theme";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const myFont = localFont({
  src: '../../public/fonts/DancingScript-Variable.ttf',
  variable: "--font-dancing-script"
});

export const metadata: Metadata = {
  title: "Unidad Didáctica",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${myFont.className}`}>
        {children}
      </body>
    </html>
  );
}
